### ISSUE TITLE
Error in setup.py

### ISSUE THREAD

**Issue by LeonLenclos** [cptx032/calcium#26]
Hi,
I was interessed using your library but when I try to `pip install` it, I got this error :
```
Complete output from command python setup.py egg_info:
    error in calcium setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'=5.0.0'"
```

**Comment by cptx032** [comment]
Hi @LeonLenclos , sorry for the late reply. I try to fix that here: https://github.com/cptx032/calcium/commit/5dade09857f29fdd4547bf256c5ccec30e95d96d

**Comment by LeonLenclos** [comment]
thank you ! 

> `Successfully installed Pillow-5.0.0 PyTweening-1.0.3 calcium-0.1.0
`
